### ISSUE TITLE
String IndexOutOfBounds Exception

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/bullrunner-gtfs-realtime-generator#9]
While working on the server, I noticed in the generator console some exceptions being thrown which appear to sometimes effect the number of vehicles/trips updated. 

The issue was tracked down to a special route called "ADM" (or similar) running in the syncromatics feed, and is fixed in the subsequent PR by simply checking that the length() of the given route (via the JSON object) is exactly 7, otherwise skipping the record entirely.

**Comment by jmfield2** [comment]
The vehicle positions and trip updates for this appear to be restored.  

It looks like there was the stringindex out of bounds issue + the new service handler (nssm) had the wrong startup directory configured (this is why there were no trips available...the GTFS is loaded from "../myGTFS/" so the startup directory needs to be \bullrunner-gtfs-realtime-generator\target)

The service parameters can be edited with:
nssm edit mobullitygtfs

**Comment by barbeau** [comment]
Thanks!  Can you please ping Sheldon and let him know its back up?

Just looked at Trips feed, most things look right, with the exception of
start_time (which is always 0), and stop_sequence, but that could be a
function of the missing stops in the GTFS data.  We should revisit once
that issue is resolved.

**Comment by jmfield2** [comment]
Fixed by 80b2899
